# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\OneDrive\Documents\GitHub\pylearn\Pylearn\UI_Files\edit_test_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(1046, 650)
        EditWindow.setMinimumSize(QtCore.QSize(1046, 650))
        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(736, 418))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bg_frame = QtWidgets.QFrame(self.centralwidget)
        self.bg_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bg_frame.setFont(font)
        self.bg_frame.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.bg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg_frame.setObjectName("bg_frame")
        self.bg_layout = QtWidgets.QVBoxLayout(self.bg_frame)
        self.bg_layout.setContentsMargins(0, 0, 0, 0)
        self.bg_layout.setSpacing(0)
        self.bg_layout.setObjectName("bg_layout")
        self.title_bar = QtWidgets.QFrame(self.bg_frame)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_bar.setStyleSheet("background-color: none")
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QFrame(self.title_bar)
        self.title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.title)
        self.verticalLayout_3.setContentsMargins(30, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.title)
        self.btn_frame = QtWidgets.QFrame(self.title_bar)
        self.btn_frame.setMaximumSize(QtCore.QSize(100, 50))
        self.btn_frame.setStyleSheet("background-color: none;")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_minimize = QtWidgets.QPushButton(self.btn_frame)
        self.btn_minimize.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_minimize.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(108, 108, 108);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/minimize_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.btn_frame)
        self.btn_maximize.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_maximize.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    image: url(:/images/icons/maxmin.png);\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(108, 108, 108);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_2.addWidget(self.btn_maximize)
        self.btn_quit = QtWidgets.QPushButton(self.btn_frame)
        self.btn_quit.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_quit.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_quit.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(255, 0, 0);\n"
"}")
        self.btn_quit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/close_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_quit.setIcon(icon1)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout_2.addWidget(self.btn_quit)
        self.horizontalLayout.addWidget(self.btn_frame)
        self.bg_layout.addWidget(self.title_bar)
        self.content_frame = QtWidgets.QFrame(self.bg_frame)
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setBold(True)
        font.setWeight(75)
        self.content_frame.setFont(font)
        self.content_frame.setStyleSheet("background-color: none")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_frame = QtWidgets.QFrame(self.content_frame)
        self.stacked_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stacked_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stacked_frame.setObjectName("stacked_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.stacked_frame)
        self.verticalLayout_4.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_frame = QtWidgets.QFrame(self.stacked_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout_8.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4.addWidget(self.title_frame)
        self.list_widget_frame = QtWidgets.QFrame(self.stacked_frame)
        self.list_widget_frame.setMinimumSize(QtCore.QSize(0, 400))
        self.list_widget_frame.setStyleSheet("color: rgb(0, 0, 0)")
        self.list_widget_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_widget_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_widget_frame.setObjectName("list_widget_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.list_widget_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.list_widget_frame)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra Regular")
        font.setPointSize(15)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    outline: 0;\n"
"} \n"
"QScrollArea::item { \n"
"    margin: 20px;\n"
"    background-color: transparent;\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QScrollBar{\n"
"    background : rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background : rgb(158, 158, 158);\n"
"    border-radius: 5px;\n"
"    margin: 3px 3px 3px 3px;\n"
"}\n"
"\n"
"QScrollBar::handle::pressed{\n"
"    background : rgb(85, 85, 85);\n"
"}\n"
"\n"
"QScrollBar::add-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.content_widget = QtWidgets.QWidget()
        self.content_widget.setGeometry(QtCore.QRect(0, 0, 1032, 502))
        self.content_widget.setObjectName("content_widget")
        self.scrollArea.setWidget(self.content_widget)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.list_widget_frame)
        self.btn_frame_2 = QtWidgets.QFrame(self.stacked_frame)
        self.btn_frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_frame_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.btn_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame_2.setObjectName("btn_frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.btn_frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(200)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(self.btn_frame_2)
        self.add_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.add_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(0, 0, 0, 150);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"}r")
        self.add_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon2)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_5.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.btn_frame_2)
        self.verticalLayout_2.addWidget(self.stacked_frame)
        self.bg_layout.addWidget(self.content_frame)
        self.frame_grip = QtWidgets.QFrame(self.bg_frame)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("background-color: none;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.bg_layout.addWidget(self.frame_grip, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.bg_frame)
        EditWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "MainWindow"))
        self.btn_quit.setShortcut(_translate("EditWindow", "Alt+X"))
import Resources_rc
