# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\OneDrive\Documents\GitHub\pylearn\Pylearn\UI_Files\edit_test_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTestFrame(object):
    def setupUi(self, EditTestFrame):
        EditTestFrame.setObjectName("EditTestFrame")
        EditTestFrame.resize(697, 152)
        EditTestFrame.setMinimumSize(QtCore.QSize(0, 0))
        EditTestFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        EditTestFrame.setFont(font)
        EditTestFrame.setStyleSheet("font: 15pt \"iCiel Effra\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(EditTestFrame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.close_frame = QtWidgets.QFrame(EditTestFrame)
        self.close_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.close_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.close_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame.setObjectName("close_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.close_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.close_btn = QtWidgets.QPushButton(self.close_frame)
        self.close_btn.setMinimumSize(QtCore.QSize(16, 16))
        self.close_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.close_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.close_btn.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(8, 8))
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout_3.addWidget(self.close_btn)
        self.verticalLayout.addWidget(self.close_frame, 0, QtCore.Qt.AlignRight)
        self.test_file_frame_2 = QtWidgets.QFrame(EditTestFrame)
        self.test_file_frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/images/icons/plus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/images/icons/minus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}")
        self.test_file_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_file_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_file_frame_2.setObjectName("test_file_frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.test_file_frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.test_file_frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    outline: 0;\n"
"} \n"
"QScrollArea::item { \n"
"    margin: 20px;\n"
"    background-color: transparent;\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QScrollBar{\n"
"    background : rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background : rgb(158, 158, 158);\n"
"    border-radius: 5px;\n"
"    margin: 3px 3px 3px 3px;\n"
"}\n"
"\n"
"QScrollBar::handle::pressed{\n"
"    background : rgb(85, 85, 85);\n"
"}\n"
"\n"
"QScrollBar::add-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 296, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_frame_2 = QtWidgets.QFrame(self.frame_4)
        self.close_frame_2.setMinimumSize(QtCore.QSize(20, 20))
        self.close_frame_2.setMaximumSize(QtCore.QSize(20, 20))
        self.close_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame_2.setObjectName("close_frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.close_frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.add_frame_btn = QtWidgets.QPushButton(self.close_frame_2)
        self.add_frame_btn.setMinimumSize(QtCore.QSize(16, 16))
        self.add_frame_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.add_frame_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_frame_btn.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        self.add_frame_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_frame_btn.setIcon(icon1)
        self.add_frame_btn.setIconSize(QtCore.QSize(8, 8))
        self.add_frame_btn.setObjectName("add_frame_btn")
        self.verticalLayout_4.addWidget(self.add_frame_btn, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.close_frame_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame)
        self.line_2 = QtWidgets.QFrame(self.test_file_frame_2)
        self.line_2.setStyleSheet("border: 2px solid rgb(255,255,255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.frame_2 = QtWidgets.QFrame(self.test_file_frame_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_5)
        self.scrollArea_2.setStyleSheet("QScrollArea {\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    outline: 0;\n"
"} \n"
"QScrollArea::item { \n"
"    margin: 20px;\n"
"    background-color: transparent;\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QScrollBar{\n"
"    background : rgb(255, 255, 255);    \n"
"}\n"
"\n"
"QScrollBar::handle{\n"
"    background : rgb(158, 158, 158);\n"
"    border-radius: 5px;\n"
"    margin: 3px 3px 3px 3px;\n"
"}\n"
"\n"
"QScrollBar::handle::pressed{\n"
"    background : rgb(85, 85, 85);\n"
"}\n"
"\n"
"QScrollBar::add-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    height: 0px;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 296, 85))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.close_frame_3 = QtWidgets.QFrame(self.frame_6)
        self.close_frame_3.setMinimumSize(QtCore.QSize(20, 20))
        self.close_frame_3.setMaximumSize(QtCore.QSize(20, 20))
        self.close_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame_3.setObjectName("close_frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.close_frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_frame_btn_2 = QtWidgets.QPushButton(self.close_frame_3)
        self.add_frame_btn_2.setMinimumSize(QtCore.QSize(16, 16))
        self.add_frame_btn_2.setMaximumSize(QtCore.QSize(16, 16))
        self.add_frame_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_frame_btn_2.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        self.add_frame_btn_2.setText("")
        self.add_frame_btn_2.setIcon(icon1)
        self.add_frame_btn_2.setIconSize(QtCore.QSize(8, 8))
        self.add_frame_btn_2.setObjectName("add_frame_btn_2")
        self.verticalLayout_5.addWidget(self.add_frame_btn_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.close_frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_4.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.test_file_frame_2)

        self.retranslateUi(EditTestFrame)
        QtCore.QMetaObject.connectSlotsByName(EditTestFrame)

    def retranslateUi(self, EditTestFrame):
        _translate = QtCore.QCoreApplication.translate
        EditTestFrame.setWindowTitle(_translate("EditTestFrame", "Form"))
import Resources_rc
