# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\OneDrive\Documents\GitHub\pylearn\Pylearn\UI_Files\edit_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditFrame(object):
    def setupUi(self, EditFrame):
        EditFrame.setObjectName("EditFrame")
        EditFrame.resize(786, 678)
        EditFrame.setMinimumSize(QtCore.QSize(0, 450))
        EditFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        EditFrame.setFont(font)
        EditFrame.setStyleSheet("font: 15pt \"iCiel Effra\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(EditFrame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.close_frame = QtWidgets.QFrame(EditFrame)
        self.close_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.close_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.close_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.close_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.close_frame.setObjectName("close_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.close_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.close_btn = QtWidgets.QPushButton(self.close_frame)
        self.close_btn.setMinimumSize(QtCore.QSize(16, 16))
        self.close_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.close_btn.setStyleSheet("QPushButton {\n"
"    background-color:transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(8, 8))
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout_3.addWidget(self.close_btn)
        self.verticalLayout.addWidget(self.close_frame, 0, QtCore.Qt.AlignRight)
        self.title_frame = QtWidgets.QFrame(EditFrame)
        self.title_frame.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.title_entry = QtWidgets.QLineEdit(self.title_frame)
        self.title_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.title_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.title_entry.setObjectName("title_entry")
        self.horizontalLayout.addWidget(self.title_entry)
        self.verticalLayout.addWidget(self.title_frame)
        self.test_file_frame = QtWidgets.QFrame(EditFrame)
        self.test_file_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/images/icons/plus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/images/icons/minus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}")
        self.test_file_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_file_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_file_frame.setObjectName("test_file_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.test_file_frame)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label_2 = QtWidgets.QLabel(self.test_file_frame)
        self.title_label_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label_2.setFont(font)
        self.title_label_2.setObjectName("title_label_2")
        self.horizontalLayout_3.addWidget(self.title_label_2)
        self.test_file_entry = QtWidgets.QLineEdit(self.test_file_frame)
        self.test_file_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.test_file_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.test_file_entry.setObjectName("test_file_entry")
        self.horizontalLayout_3.addWidget(self.test_file_entry)
        self.test_file_btn = QtWidgets.QPushButton(self.test_file_frame)
        self.test_file_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.test_file_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.test_file_btn.setFont(font)
        self.test_file_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150)\n"
"}")
        self.test_file_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.test_file_btn.setIcon(icon1)
        self.test_file_btn.setCheckable(False)
        self.test_file_btn.setChecked(False)
        self.test_file_btn.setFlat(False)
        self.test_file_btn.setObjectName("test_file_btn")
        self.horizontalLayout_3.addWidget(self.test_file_btn)
        self.verticalLayout.addWidget(self.test_file_frame)
        self.info_frame = QtWidgets.QFrame(EditFrame)
        self.info_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(209, 209, 209);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(:/images/icons/plus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(:/images/icons/minus.png);\n"
"    width: 10px;\n"
"    height: 20px;\n"
"}")
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.info_frame)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.title_label_4 = QtWidgets.QLabel(self.info_frame)
        self.title_label_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label_4.setFont(font)
        self.title_label_4.setObjectName("title_label_4")
        self.horizontalLayout_6.addWidget(self.title_label_4)
        self.info_file_entry = QtWidgets.QLineEdit(self.info_frame)
        self.info_file_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.info_file_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.info_file_entry.setObjectName("info_file_entry")
        self.horizontalLayout_6.addWidget(self.info_file_entry)
        self.info_file_btn = QtWidgets.QPushButton(self.info_frame)
        self.info_file_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.info_file_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.info_file_btn.setFont(font)
        self.info_file_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150)\n"
"}")
        self.info_file_btn.setText("")
        self.info_file_btn.setIcon(icon1)
        self.info_file_btn.setCheckable(False)
        self.info_file_btn.setChecked(False)
        self.info_file_btn.setFlat(False)
        self.info_file_btn.setObjectName("info_file_btn")
        self.horizontalLayout_6.addWidget(self.info_file_btn)
        self.line_4 = QtWidgets.QFrame(self.info_frame)
        self.line_4.setStyleSheet("border: 2px solid rgb(255,255,255);\n"
"")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.info_frame)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.Score_edit = QtWidgets.QSpinBox(self.info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Score_edit.sizePolicy().hasHeightForWidth())
        self.Score_edit.setSizePolicy(sizePolicy)
        self.Score_edit.setMinimumSize(QtCore.QSize(45, 40))
        self.Score_edit.setStyleSheet("")
        self.Score_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_edit.setMinimum(1)
        self.Score_edit.setMaximum(100)
        self.Score_edit.setProperty("value", 1)
        self.Score_edit.setDisplayIntegerBase(10)
        self.Score_edit.setObjectName("Score_edit")
        self.horizontalLayout_6.addWidget(self.Score_edit)
        self.verticalLayout.addWidget(self.info_frame)
        self.details_frame = QtWidgets.QFrame(EditFrame)
        self.details_frame.setMinimumSize(QtCore.QSize(0, 200))
        self.details_frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.details_frame.setStyleSheet("background-color: rgb(209, 209, 209);")
        self.details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.details_frame.setObjectName("details_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.details_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.details_label = QtWidgets.QLabel(self.details_frame)
        font = QtGui.QFont()
        font.setFamily("iCiel Effra")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.details_label.setFont(font)
        self.details_label.setObjectName("details_label")
        self.verticalLayout_2.addWidget(self.details_label)
        self.details_entry = QtWidgets.QTextEdit(self.details_frame)
        self.details_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.details_entry.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.details_entry.setObjectName("details_entry")
        self.verticalLayout_2.addWidget(self.details_entry)
        self.verticalLayout.addWidget(self.details_frame)

        self.retranslateUi(EditFrame)
        QtCore.QMetaObject.connectSlotsByName(EditFrame)

    def retranslateUi(self, EditFrame):
        _translate = QtCore.QCoreApplication.translate
        EditFrame.setWindowTitle(_translate("EditFrame", "Form"))
        self.title_label.setText(_translate("EditFrame", "Tên bài tập:"))
        self.title_label_2.setText(_translate("EditFrame", "File test:"))
        self.title_label_4.setText(_translate("EditFrame", "File chú thích:"))
        self.label_4.setText(_translate("EditFrame", "Điểm:"))
        self.details_label.setText(_translate("EditFrame", "Chi tiết bài tập:"))
import Resources_rc
