# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Documents\GitHub\pylearn\Pylearn\new gui\hello Tien ne ku\Loading_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loading_Screen(object):
    def setupUi(self, Loading_Screen):
        Loading_Screen.setObjectName("Loading_Screen")
        Loading_Screen.resize(717, 315)
        Loading_Screen.setStyleSheet("border-radius: 40px;")
        self.centralwidget = QtWidgets.QWidget(Loading_Screen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Loading_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Loading_Frame.setStyleSheet("QFrame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.9945, y2:1, stop:0.125 rgba(129, 48, 142, 255), stop:1 rgba(63, 31, 95, 255));\n"
"}")
        self.Loading_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Loading_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Loading_Frame.setObjectName("Loading_Frame")
        self.Slogan_Pylearn = QtWidgets.QLabel(self.Loading_Frame)
        self.Slogan_Pylearn.setGeometry(QtCore.QRect(80, 20, 221, 81))
        self.Slogan_Pylearn.setStyleSheet("QLabel {\n"
"background: none;\n"
"color:  rgb(255, 170, 255);\n"
"font: bold;\n"
"font-size: 40px;\n"
"}")
        self.Slogan_Pylearn.setObjectName("Slogan_Pylearn")
        self.Slogan = QtWidgets.QLabel(self.Loading_Frame)
        self.Slogan.setGeometry(QtCore.QRect(250, 60, 261, 41))
        self.Slogan.setStyleSheet("QLabel {\n"
"background: none;\n"
"color: rgb(213, 41, 255);\n"
"font-size: 20px;\n"
"}")
        self.Slogan.setObjectName("Slogan")
        self.progressBar = QtWidgets.QProgressBar(self.Loading_Frame)
        self.progressBar.setGeometry(QtCore.QRect(120, 160, 511, 40))
        self.progressBar.setStyleSheet("QProgressBar {     \n"
"    border-radius: 20px;\n"
"     color: rgb(255, 170, 255);\n"
"     font: bold;\n"
"    font-size: 20px;\n"
"    text-align: center;\n"
"    background-color: rgba(154, 57, 171, 100);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 20px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.579, stop:0 rgba(210, 93, 255, 255), stop:0.642045 rgba(142, 32, 201, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Loading_label = QtWidgets.QLabel(self.Loading_Frame)
        self.Loading_label.setGeometry(QtCore.QRect(350, 200, 261, 41))
        self.Loading_label.setStyleSheet("QLabel {\n"
"background: none;\n"
"color: rgb(170, 85, 255);\n"
"font-size: 18px;\n"
"}")
        self.Loading_label.setObjectName("Loading_label")
        self.label_credits = QtWidgets.QLabel(self.Loading_Frame)
        self.label_credits.setGeometry(QtCore.QRect(-10, 290, 651, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("background: none;\n"
"color: rgb(98, 114, 164);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout.addWidget(self.Loading_Frame)
        Loading_Screen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Loading_Screen)
        QtCore.QMetaObject.connectSlotsByName(Loading_Screen)

    def retranslateUi(self, Loading_Screen):
        _translate = QtCore.QCoreApplication.translate
        Loading_Screen.setWindowTitle(_translate("Loading_Screen", "MainWindow"))
        self.Slogan_Pylearn.setText(_translate("Loading_Screen", "PyLearn"))
        self.Slogan.setText(_translate("Loading_Screen", "ỨNG DỤNG HỌC TẬP"))
        self.Loading_label.setText(_translate("Loading_Screen", "loading ..."))
        self.label_credits.setText(_translate("Loading_Screen", "<strong>Created</strong>: Tien Huynh @Tok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Loading_Screen = QtWidgets.QMainWindow()
    ui = Ui_Loading_Screen()
    ui.setupUi(Loading_Screen)
    Loading_Screen.show()
    sys.exit(app.exec_())
