# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Documents\GitHub\pylearn\Pylearn\new gui\NewGUI_Login\Login_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("border-radius: 8px;\n"
"background-color:none;")
        self.Form = QtWidgets.QWidget(MainWindow)
        self.Form.setObjectName("Form")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Form)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bg_frame = QtWidgets.QFrame(self.Form)
        self.bg_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bg_frame.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.591, stop:0.227273 rgba(94, 0, 95, 255), stop:1 rgba(0, 0, 45, 255));\n"
" border: none;\n"
"}")
        self.bg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg_frame.setObjectName("bg_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.bg_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.title_bar = QtWidgets.QFrame(self.bg_frame)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 20))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.title_bar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_frame = QtWidgets.QFrame(self.title_bar)
        self.btn_frame.setMaximumSize(QtCore.QSize(100, 50))
        self.btn_frame.setStyleSheet("background-color: none;")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btn_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_quit = QtWidgets.QPushButton(self.btn_frame)
        self.btn_quit.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_quit.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_quit.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_quit.setText("")
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout_2.addWidget(self.btn_quit)
        self.btn_minimize = QtWidgets.QPushButton(self.btn_frame)
        self.btn_minimize.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_2.addWidget(self.btn_minimize)
        self.horizontalLayout_3.addWidget(self.btn_frame)
        self.label_11 = QtWidgets.QLabel(self.title_bar)
        self.label_11.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"text-align: left;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.gridLayout.addWidget(self.title_bar, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.bg_frame)
        self.frame.setEnabled(True)
        self.frame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame.setToolTipDuration(-1)
        self.frame.setStyleSheet("background-color: none;\n"
"border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.SignIn_Frame = QtWidgets.QFrame(self.frame)
        self.SignIn_Frame.setGeometry(QtCore.QRect(40, 210, 421, 291))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SignIn_Frame.setFont(font)
        self.SignIn_Frame.setStyleSheet("QFrame { \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0227273 rgba(150, 0, 183, 150), stop:1 rgba(255, 255, 255, 150));\n"
"border-radius: 8px;\n"
"}")
        self.SignIn_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SignIn_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SignIn_Frame.setObjectName("SignIn_Frame")
        self.label = QtWidgets.QLabel(self.SignIn_Frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(225, 255, 255);\n"
"background-color: none;\n"
"text-align: center;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.NameBox_SI = QtWidgets.QLineEdit(self.SignIn_Frame)
        self.NameBox_SI.setGeometry(QtCore.QRect(70, 90, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.NameBox_SI.setFont(font)
        self.NameBox_SI.setStyleSheet("QLineEdit {\n"
"background-color: rgba(188, 183, 255, 160);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 255, 255);\n"
"color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.NameBox_SI.setMaxLength(225)
        self.NameBox_SI.setAlignment(QtCore.Qt.AlignCenter)
        self.NameBox_SI.setObjectName("NameBox_SI")
        self.PassBox_SI = QtWidgets.QLineEdit(self.SignIn_Frame)
        self.PassBox_SI.setGeometry(QtCore.QRect(70, 140, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.PassBox_SI.setFont(font)
        self.PassBox_SI.setToolTip("")
        self.PassBox_SI.setStyleSheet("QLineEdit {\n"
"background-color: rgba(188, 183, 255, 160);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 255, 255);\n"
"color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.PassBox_SI.setLocale(QtCore.QLocale(QtCore.QLocale.Vietnamese, QtCore.QLocale.Vietnam))
        self.PassBox_SI.setMaxLength(225)
        self.PassBox_SI.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassBox_SI.setAlignment(QtCore.Qt.AlignCenter)
        self.PassBox_SI.setObjectName("PassBox_SI")
        self.SignIn_Bt = QtWidgets.QPushButton(self.SignIn_Frame)
        self.SignIn_Bt.setGeometry(QtCore.QRect(160, 190, 81, 21))
        self.SignIn_Bt.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 85, 255,160);\n"
"border-radius: 8px;\n"
"color: rgb(255, 255, 255);\n"
"font: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 170, 255);\n"
"}\n"
"QPushButton:focus {\n"
"background-color:rgb(255, 170, 255);\n"
"}")
        self.SignIn_Bt.setFlat(True)
        self.SignIn_Bt.setObjectName("SignIn_Bt")
        self.label_3 = QtWidgets.QLabel(self.SignIn_Frame)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"color: rgb(255,255,255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.SignIn_Frame)
        self.label_4.setGeometry(QtCore.QRect(70, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"color: rgb(255,255,255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.SignIn_Frame)
        self.checkBox.setGeometry(QtCore.QRect(240, 170, 111, 21))
        self.checkBox.setStyleSheet("font: bold;\n"
"color: rgb(255, 255, 255)")
        self.checkBox.setObjectName("checkBox")
        self.ConvertButton = QtWidgets.QPushButton(self.SignIn_Frame)
        self.ConvertButton.setGeometry(QtCore.QRect(70, 220, 251, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ConvertButton.setFont(font)
        self.ConvertButton.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 85, 255,0);\n"
"border-radius: 8px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(170, 255, 255);\n"
"}")
        self.ConvertButton.setAutoRepeat(True)
        self.ConvertButton.setObjectName("ConvertButton")
        self.Complete_Frame = QtWidgets.QFrame(self.frame)
        self.Complete_Frame.setEnabled(True)
        self.Complete_Frame.setGeometry(QtCore.QRect(40, 210, 421, 291))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Complete_Frame.setFont(font)
        self.Complete_Frame.setStyleSheet("QFrame { \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0227273 rgba(150, 0, 183, 150), stop:1 rgba(255, 255, 255, 150));\n"
"border-radius: 8px;\n"
"}")
        self.Complete_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Complete_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Complete_Frame.setObjectName("Complete_Frame")
        self.label_10 = QtWidgets.QLabel(self.Complete_Frame)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(225, 255, 255);\n"
"background-color: none;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.ConvertButton_4 = QtWidgets.QPushButton(self.Complete_Frame)
        self.ConvertButton_4.setEnabled(True)
        self.ConvertButton_4.setGeometry(QtCore.QRect(100, 190, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ConvertButton_4.setFont(font)
        self.ConvertButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 85, 255,0);\n"
"border-radius: 8px;\n"
"color: rgb(170, 170, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: none;\n"
"color: rgb(255,255,255);\n"
"}")
        self.ConvertButton_4.setAutoRepeat(True)
        self.ConvertButton_4.setObjectName("ConvertButton_4")
        self.SignUp_Frame = QtWidgets.QFrame(self.frame)
        self.SignUp_Frame.setEnabled(True)
        self.SignUp_Frame.setGeometry(QtCore.QRect(40, 210, 421, 291))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SignUp_Frame.setFont(font)
        self.SignUp_Frame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.SignUp_Frame.setToolTip("")
        self.SignUp_Frame.setToolTipDuration(10)
        self.SignUp_Frame.setStyleSheet("QFrame { \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0227273 rgba(150, 0, 183, 150), stop:1 rgba(255, 255, 255, 150));\n"
"border-radius: 8px;\n"
"}")
        self.SignUp_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SignUp_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SignUp_Frame.setObjectName("SignUp_Frame")
        self.label_7 = QtWidgets.QLabel(self.SignUp_Frame)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(225, 255, 255);\n"
"background-color: none;\n"
"text-align: center;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.NameBox_SU = QtWidgets.QLineEdit(self.SignUp_Frame)
        self.NameBox_SU.setEnabled(True)
        self.NameBox_SU.setGeometry(QtCore.QRect(70, 90, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.NameBox_SU.setFont(font)
        self.NameBox_SU.setToolTip("<html><head/><body><p><span style=\" font-weight:600; color:#ff0800;\">Tên đăng nhập tối thiểu 6 kí tự, chứa kí tự bao gồm [0-9,a-z,A-Z,_,  ]</span></p></body></html>")
        self.NameBox_SU.setStyleSheet("QLineEdit {\n"
"background-color: rgba(188, 183, 255, 160);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 255, 255);\n"
"color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.NameBox_SU.setAlignment(QtCore.Qt.AlignCenter)
        self.NameBox_SU.setObjectName("NameBox_SU")
        self.PassBox_SU = QtWidgets.QLineEdit(self.SignUp_Frame)
        self.PassBox_SU.setGeometry(QtCore.QRect(70, 140, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.PassBox_SU.setFont(font)
        self.PassBox_SU.setToolTip("")
        self.PassBox_SU.setStyleSheet("QLineEdit {\n"
"background-color: rgba(188, 183, 255, 160);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 255, 255);\n"
"color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.PassBox_SU.setMaxLength(225)
        self.PassBox_SU.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassBox_SU.setAlignment(QtCore.Qt.AlignCenter)
        self.PassBox_SU.setObjectName("PassBox_SU")
        self.SignUp_Bt = QtWidgets.QPushButton(self.SignUp_Frame)
        self.SignUp_Bt.setGeometry(QtCore.QRect(160, 200, 81, 21))
        self.SignUp_Bt.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 85, 255,160);\n"
"border-radius: 8px;\n"
"color: rgb(255, 255, 255);\n"
"font: bold;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 170, 255);\n"
"}\n"
"QPushButton:focus {\n"
"background-color:rgb(255, 170, 255);\n"
"}")
        self.SignUp_Bt.setFlat(True)
        self.SignUp_Bt.setObjectName("SignUp_Bt")
        self.label_8 = QtWidgets.QLabel(self.SignUp_Frame)
        self.label_8.setGeometry(QtCore.QRect(70, 120, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(255,255,255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.SignUp_Frame)
        self.label_9.setGeometry(QtCore.QRect(70, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(255,255,255);\n"
"")
        self.label_9.setObjectName("label_9")
        self.ConvertButton_3 = QtWidgets.QPushButton(self.SignUp_Frame)
        self.ConvertButton_3.setGeometry(QtCore.QRect(80, 230, 251, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ConvertButton_3.setFont(font)
        self.ConvertButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 85, 255,0);\n"
"border-radius: 8px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"color: rgb(170, 255, 255);\n"
"}")
        self.ConvertButton_3.setAutoRepeat(True)
        self.ConvertButton_3.setObjectName("ConvertButton_3")
        self.Student_SU = QtWidgets.QRadioButton(self.SignUp_Frame)
        self.Student_SU.setGeometry(QtCore.QRect(110, 170, 82, 17))
        self.Student_SU.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: bold;")
        self.Student_SU.setChecked(True)
        self.Student_SU.setObjectName("Student_SU")
        self.Teacher_SU = QtWidgets.QRadioButton(self.SignUp_Frame)
        self.Teacher_SU.setGeometry(QtCore.QRect(220, 170, 82, 17))
        self.Teacher_SU.setStyleSheet("font: bold;\n"
"color: rgb(255, 255, 255)")
        self.Teacher_SU.setObjectName("Teacher_SU")
        self.ConvertButton_3.raise_()
        self.label_7.raise_()
        self.NameBox_SU.raise_()
        self.PassBox_SU.raise_()
        self.SignUp_Bt.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Student_SU.raise_()
        self.Teacher_SU.raise_()
        self.frameError = QtWidgets.QFrame(self.frame)
        self.frameError.setGeometry(QtCore.QRect(230, 180, 311, 51))
        self.frameError.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.9945, y2:1, stop:0.125 rgba(129, 48, 142, 160), stop:1 rgba(63, 31, 95, 200));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"}")
        self.frameError.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameError.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameError.setObjectName("frameError")
        self.Error_SpecialCr = QtWidgets.QLabel(self.frameError)
        self.Error_SpecialCr.setGeometry(QtCore.QRect(50, 10, 281, 31))
        self.Error_SpecialCr.setStyleSheet("background: none;\n"
"font: bold;\n"
"font-size: 12px;")
        self.Error_SpecialCr.setObjectName("Error_SpecialCr")
        self.Error_PassRan = QtWidgets.QLabel(self.frameError)
        self.Error_PassRan.setGeometry(QtCore.QRect(40, 10, 281, 31))
        self.Error_PassRan.setStyleSheet("background: none;\n"
"font: bold;\n"
"font-size: 12px;")
        self.Error_PassRan.setObjectName("Error_PassRan")
        self.Error_NameRan = QtWidgets.QLabel(self.frameError)
        self.Error_NameRan.setGeometry(QtCore.QRect(20, 10, 281, 31))
        self.Error_NameRan.setStyleSheet("background: none;\n"
"font: bold;\n"
"font-size: 12px;")
        self.Error_NameRan.setObjectName("Error_NameRan")
        self.Error_NamePass = QtWidgets.QLabel(self.frameError)
        self.Error_NamePass.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.Error_NamePass.setStyleSheet("background: none;\n"
"font: bold;\n"
"font-size: 12px;")
        self.Error_NamePass.setObjectName("Error_NamePass")
        self.OkCancelFrame = QtWidgets.QFrame(self.frame)
        self.OkCancelFrame.setGeometry(QtCore.QRect(290, 200, 400, 180))
        self.OkCancelFrame.setStyleSheet("QFrame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.579, stop:0 rgba(210, 93, 255, 160), stop:0.642045 rgba(142, 32, 201, 160));\n"
"color: rgb(170, 255, 255);\n"
"border-radius: 50px;\n"
"}")
        self.OkCancelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OkCancelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OkCancelFrame.setObjectName("OkCancelFrame")
        self.Accept = QtWidgets.QPushButton(self.OkCancelFrame)
        self.Accept.setGeometry(QtCore.QRect(60, 130, 100, 20))
        self.Accept.setStyleSheet("QPushButton {\n"
"border-radius:10;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(181, 67, 232);\n"
"font: bold;\n"
"font-size: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Accept.setObjectName("Accept")
        self.Deny = QtWidgets.QPushButton(self.OkCancelFrame)
        self.Deny.setGeometry(QtCore.QRect(230, 130, 100, 20))
        self.Deny.setToolTip("")
        self.Deny.setStyleSheet("QPushButton {\n"
"border-radius:10;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(142, 32, 201);\n"
"font: bold;\n"
"font-size: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(255, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Deny.setCheckable(True)
        self.Deny.setChecked(True)
        self.Deny.setAutoRepeat(False)
        self.Deny.setAutoExclusive(True)
        self.Deny.setObjectName("Deny")
        self.label_2 = QtWidgets.QLabel(self.OkCancelFrame)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 321, 41))
        self.label_2.setStyleSheet("background-color: none;\n"
"font:bold;\n"
"font-size: 16px;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.Complete_Frame.raise_()
        self.SignIn_Frame.raise_()
        self.SignUp_Frame.raise_()
        self.frameError.raise_()
        self.OkCancelFrame.raise_()
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)
        self.frame_grip = QtWidgets.QFrame(self.bg_frame)
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("QFrame {\n"
"background-color: none;\n"
"border-radius: 12px;\n"
"}\n"
"QFrame:hover{\n"
"background-color: rgb(66, 0, 99);\n"
"border-radius: 12px;\n"
"}")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.gridLayout.addWidget(self.frame_grip, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.bg_frame)
        MainWindow.setCentralWidget(self.Form)

        self.retranslateUi(MainWindow)
        self.ConvertButton.clicked.connect(self.SignIn_Frame.hide)
        self.ConvertButton.clicked.connect(self.SignUp_Frame.show)
        self.ConvertButton_3.clicked.connect(self.SignIn_Frame.show)
        self.ConvertButton_3.clicked.connect(self.SignUp_Frame.hide)
        self.ConvertButton_4.clicked.connect(self.SignIn_Frame.show)
        self.ConvertButton_4.clicked.connect(self.Complete_Frame.hide)
        self.frameError.customContextMenuRequested['QPoint'].connect(self.Error_SpecialCr.hide)
        self.SignUp_Bt.clicked.connect(self.Error_NameRan.hide)
        self.SignUp_Bt.clicked.connect(self.Error_SpecialCr.hide)
        self.SignUp_Bt.clicked.connect(self.Error_PassRan.hide)
        self.ConvertButton.clicked.connect(self.NameBox_SU.clear)
        self.ConvertButton.clicked.connect(self.PassBox_SU.clear)
        self.ConvertButton_3.clicked.connect(self.NameBox_SI.clear)
        self.ConvertButton_3.clicked.connect(self.PassBox_SI.clear)
        self.ConvertButton.clicked.connect(self.Student_SU.toggle)
        self.Deny.clicked.connect(self.OkCancelFrame.close)
        self.Accept.clicked.connect(self.OkCancelFrame.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_quit.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">PyLearn - Đăng nhập hệ thống</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<STRONG>ĐĂNG NHẬP TÀI KHOẢN</STRONG>"))
        self.NameBox_SI.setPlaceholderText(_translate("MainWindow", "Nhập tên tài khoản của bạn"))
        self.PassBox_SI.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu của bạn"))
        self.SignIn_Bt.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu:"))
        self.label_4.setText(_translate("MainWindow", "Tên tài khoản:"))
        self.checkBox.setText(_translate("MainWindow", "Lưu đăng nhập?"))
        self.ConvertButton.setText(_translate("MainWindow", "Không có tài khoản? Đăng ký ngay"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ĐĂNG KÝ HOÀN TẤT</span></p></body></html>"))
        self.ConvertButton_4.setText(_translate("MainWindow", "Trở về"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ĐĂNG KÍ TÀI KHOẢN</span></p></body></html>"))
        self.NameBox_SU.setPlaceholderText(_translate("MainWindow", "Nhập tên tài khoản đăng ký của bạn"))
        self.PassBox_SU.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu đăng ký của bạn"))
        self.SignUp_Bt.setText(_translate("MainWindow", "Đăng kí"))
        self.label_8.setText(_translate("MainWindow", "Mật khẩu:"))
        self.label_9.setText(_translate("MainWindow", "Tên tài khoản:"))
        self.ConvertButton_3.setText(_translate("MainWindow", "Quay trở về khung đăng nhập"))
        self.Student_SU.setText(_translate("MainWindow", "Học sinh"))
        self.Teacher_SU.setText(_translate("MainWindow", "Giáo viên"))
        self.Error_SpecialCr.setText(_translate("MainWindow", "Yêu cầu không chứa kí tự đặc biệt"))
        self.Error_PassRan.setText(_translate("MainWindow", "Yêu cầu độ dài mật khẩu ít nhất 3 kí tự"))
        self.Error_NameRan.setText(_translate("MainWindow", "Yêu cầu độ dài tên tài khoản ít nhất 6 kí tự"))
        self.Error_NamePass.setText(_translate("MainWindow", "Yêu cầu nhập đầy đủ tên tài khoản, mật khẩu"))
        self.Accept.setText(_translate("MainWindow", "Chấp nhận"))
        self.Deny.setText(_translate("MainWindow", "Từ chối"))
        self.label_2.setText(_translate("MainWindow", "Xác nhận thoát giao diện đăng nhập?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
